version: "3.0"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - "mongodb"
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"